### ISSUE TITLE
Remove stdlib dependency

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive-template#3]
Hi,

This is a similar issue with https://github.com/mtymek/expressive-config-manager/issues/9.

I'm having various issues currently with conflicting versions, as Stdlib includes too much code, has dependency to unrelated stuff (mainly hydrator), which poses some issue for nothing.

I'd suggest that this package adds a trait "ArrayMergeTrait", that uses the code from the merge method in Stdlib, so dependency to Stdlib can be removed from all templates project.

I can do the PR if you want.

**Comment by weierophinney** [comment]
@bakura10 That would be fine. However, there are some details in the `ArrayUtils::merge()` functionality that are not easily ported: two interfaces exist to allow configuration writers to signal what behavior to implement when merging specific values (replace/remove, respectively), and having multiple ways to signal that information between components will quickly lead to issues. You can see these problems in zendframework/zend-servicemanager#68.

Ideally, any pull request you do follows the approach from that pull request, once it's finalized.

**Comment by weierophinney** [comment]
We inlined the logic some time ago... and it's now removed entire, so I'm closing this.
